version: "2"
services:
  samson:
    image: anthony2020/samson:latest 
    ports:
      - "3000:9080"
    volumes:
      - .:/app/
    environment:
      DATABASE_URL: "sqlite3:///app/db/development.sqlite3"
      RAILS_LOG_TO_STDOUT: 1
    command: ["./script/docker_dev_server"]
